config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end

  resources :comments

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    # 요청에서 들어오는 URL 파라미터 변수에서 :post_id를 획득하여 Post를 조회하고
    @post = Post.find(params[:post_id])
    # 그 모델이 가지는 Comments의 관계를 연결하여 이것을 저장
    @comment = @post.comments.build(comment_params)

    if @comment.save
      # Ajax를 사용하기 때문에 컨트롤러가 뷰를 응답할 때, JavaScript로 응답하도록 한다.
      # 이 때 format.js로 지정한 뷰의 응답은 create 메소드의 이름과 동일한 JavaScript 파일로 app/views/comments/create.js.erb 라는 이름의 파일과 매핑된다
      respond_to do |format|
        format.js
      end
    else

    end
  end

  def destroy
   @comment = Comment.find(params[:id])
   if @comment.destroy
     respond_to do |format|
       format.js
     end
   end
  end
  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_item.html.erb
<!--Partial을 사용하여 복잡한 뷰를 구조화 -->
<!--Rails에서의 Partial은 뷰 레이아웃을 렌더링 할 때 복잡하거나 반복적인 뷰를 단순화 시키고 재활용하기 위해 사용한다-->
<li><%= comment.content %></li>

<li id="comment-<%=comment.id%>">
  <%= comment.content %>
  <%= link_to "Delete", comment_path(comment),
                        method: :delete,
                        remote: true,
                        data: {confirm: "Are you sure?"} %>
</li>

app/views/comments/create.js.erb
// Comment를 저장한 이후 입력폼을 비우고,
// Comments 목록을 출력하는 DOM에 저장한 Comment 내용을 추가하는 코드
(function($){
  // comment_content에 있는 텍스트 필드값을 .val()안의 값으로 변경
  $("#comment_content").val("")
  // $("#comments").append("<li><%=@comment.content%></li>");
  var html = "<%= escape_javascript(render(partial: 'comments/item', locals: {comment: @comment})) %>";
  $("#comments").append(html);
})(jQuery)

app/views/comments/destory.js.erb
// 해당하는 comment의 id를 가지고 DOM에서 해당 comment를 제거하는 코드
// Ajax로 comment를 삭제한 요청이 완료된 이후 destory.js.erb에서 해당하는 DOM에서 comment를 쉽게 제거하기 위해
// DOM에 id="comment-<%=comment.id%>”로 유일한 id를 지정
(function($){
  $("#comment-<%= @comment.id %>").remove();
})(jQuery)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AjaxPartial</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Comments</strong>
  <ui id = "comments">
    <% @post.comments.each do |comment| %>
      <!-- <li><%=  comment.content %></li> -->
      <%= render partial: "comments/item", locals: { comment: comment } %>
    <% end %>
  </ui>
</p>

<p>
  <%= form_for [@post, @post.comments.new], remote: true do |f| %>
    <%= f.text_area :content %>
    <%= f.submit %>
  <% end %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>